### ISSUE TITLE
how to use it on mac os m2/m3 chips

### ISSUE THREAD

**Issue by guobuchi** [AWehrhahn/SME#71]
how to use it on mac os m2/m3 chips

**Comment by guosufen** [comment]
I have tested the following steps to use pysme on mac os m2/ m3 chips, it works well.

1. Download the SMElib from AWehrhahn's github respository.
2. Compile the SMElib according the instructions in the 'readme.md'. Make sure to use the arm64 version of gortran on your mac. The resulting library files ( libsme.la, libsme.dylib, libsme.5.dylib, sme_synth.so.darwin.aarch64.64) will be located in the '/usr/local/lib/' dictory (this may vary depending on your setup).
3. Replace these 4 files in the original directory, typically found at '/opt/miniconda3/envs/env_name/lib/python3.11/site-packages/pysme/lib/'
4. Uninstall pysme using "pip uninstall pysme-astro". This usually does not remove the lib directory.
5. Reinstall the pysme. Done!
